version: '3.7'

services:
    app:
        build: .
        container_name: rentx
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
    database:
        image: postgres
        container_name: database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
